language: ruby
rvm:
  - 2.1.0

script: ./script/cibuild

cache: bundler
sudo: false

before_script:
  - bundle exec jekyll build

script:
  - bundle exec rake test

# branch whitelist
branches:
  only:
    - master # test the master branch

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
